version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 7.4-apache
    depends_on:
      - db
    ports:
      - 8000:80
    volumes:
      - .:/var/www/
      - ./DockerConfig/fqdn:/etc/apache2/conf.d/fqdn
      - ./DockerConfig/apache2:/etc/apache2/sites-enabled/
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./DockerMysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
    restart: always
    ports:
      - 6603:3306
  redis:
    image: redis:alpine
